### ISSUE TITLE
Booleans are being converted into string

### ISSUE THREAD

**Issue by dxvargas** [grasmash/expander#6]
When expanding an array where a placeholder is to be replaced with a boolean, it will be replaced either by '' or '-1' values.

I have prepared this Pull Request where the existing test covers this situation: https://github.com/grasmash/expander/pull/5
So it fails: `Failed asserting that '1' is of type "boolean".`

Would like to have some feedback about this. Can we fix it?

**Comment by grasmash** [comment]
Root cause is that `expandStringProperties()` uses `preg_replace_callback()`, which always returns a string.

This is tricky. You basically want `${expand-boolean}` to return as boolean but `${expand-boolean} ${expand-other}` to return as a string. To make thin work, we'd need `expandStringProperties()` to somehow determine if the value is a placeholder for only a single property, and then treat it differently.
